#! /bin/sh

# Installation
# - Move this to /etc/init.d/myservice
# - chmod +x this
#
# Starting and stopping
# - Start: `service myservice start` or `/etc/init.d/myservice start`
# - Stop: `service myservice stop` or `/etc/init.d/myservice stop`

#ref http://till.klampaeckel.de/blog/archives/94-start-stop-daemon,-Gearman-and-a-little-PHP.html
#ref http://unix.stackexchange.com/questions/85033/use-start-stop-daemon-for-a-php-server/85570#85570
#ref http://serverfault.com/questions/229759/launching-a-php-daemon-from-an-lsb-init-script-w-start-stop-daemon

NAME=php_chatserver
DESC="Daemon for my magnificent PHP CLI script"
PIDFILE="/var/run/${NAME}.pid"
LOGFILE="/var/log/${NAME}.log"

DAEMON="/usr/bin/php"
DAEMON_OPTS="/var/www/html/chat_server/server.php"

START_OPTS="--start --background --make-pidfile --pidfile ${PIDFILE} --exec ${DAEMON} -q ${DAEMON_OPTS}"
STOP_OPTS="--stop --pidfile ${PIDFILE}"

test -x $DAEMON || exit 1

set -e

case "$1" in
    start)
        
        start-stop-daemon $START_OPTS >> $LOGFILE && echo '{"error":"0","message":"Sunucu başarıyla başlatıldı"}' || echo '{"error":"1","message":"Sunucu başlatılırken bir hata oluştu"}'
        ;;
    stop)
        start-stop-daemon $STOP_OPTS >/dev/null && echo '{"error":"0","message":"Sunucu başarıyla durduruldu"}' || echo '{"error":"1","message":"Sunucu durdurulurken bir hata oluştu"}'
        rm -f $PIDFILE
        ;;
    restart|force-reload)
        start-stop-daemon $STOP_OPTS >/dev/null
        sleep 1
        start-stop-daemon $START_OPTS >> $LOGFILE && echo '{"error":"0","message":"Sunucu başarıyla yeniden başlatıldı"}' || echo '{"error":"1","message":"Sunucu yeniden başlatılırken bir hata oluştu"}'
        ;;
    *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload}" >&2
        exit 1
        ;;
esac

exit 0