#!/bin/sh
 
# The init commands
case "$1" in
        start)
                
                /etc/init.d/icecast2 start >/dev/null  && echo '{"error":"0","message":"Sunucu başarıyla başlatıldı"}' || echo '{"error":"1","message":"Sunucu başlatılırken bir hata oluştu"}'

                ;;
        stop)
               	autodj stop >/dev/null
                /etc/init.d/icecast2 stop >/dev/null  && echo '{"error":"0","message":"Sunucu başarıyla durduruldu"}' || echo '{"error":"1","message":"Sunucu durdurulurken bir hata oluştu"}'
                ;;
        restart)
		autodj stop >/dev/null
                /etc/init.d/icecast2 restart >/dev/null && echo '{"error":"0","message":"Sunucu başarıyla yeniden başlatıldı"}' || echo '{"error":"1","message":"Sunucu yeniden başlatılırken bir hata oluştu"}'
                ;;
        *)
                echo "usage: /etc/init.d/shoutcast"
                echo "$0 {start | stop | restart}"
                exit 1
                ;;
esac
